// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package twingate

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetTwingateConnectors(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetTwingateConnectorsResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetTwingateConnectorsResult
	err := ctx.Invoke("twingate:index/getTwingateConnectors:getTwingateConnectors", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getTwingateConnectors.
type GetTwingateConnectorsResult struct {
	Connectors []GetTwingateConnectorsConnector `pulumi:"connectors"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}
