// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TwingateLabs.Twingate
{
    public static class GetTwingateResource
    {
        public static Task<GetTwingateResourceResult> InvokeAsync(GetTwingateResourceArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetTwingateResourceResult>("twingate:index/getTwingateResource:getTwingateResource", args ?? new GetTwingateResourceArgs(), options.WithDefaults());

        public static Output<GetTwingateResourceResult> Invoke(GetTwingateResourceInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetTwingateResourceResult>("twingate:index/getTwingateResource:getTwingateResource", args ?? new GetTwingateResourceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTwingateResourceArgs : Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetTwingateResourceArgs()
        {
        }
    }

    public sealed class GetTwingateResourceInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetTwingateResourceInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetTwingateResourceResult
    {
        public readonly string Address;
        public readonly string Id;
        public readonly string Name;
        public readonly ImmutableArray<Outputs.GetTwingateResourceProtocolResult> Protocols;
        public readonly string RemoteNetworkId;

        [OutputConstructor]
        private GetTwingateResourceResult(
            string address,

            string id,

            string name,

            ImmutableArray<Outputs.GetTwingateResourceProtocolResult> protocols,

            string remoteNetworkId)
        {
            Address = address;
            Id = id;
            Name = name;
            Protocols = protocols;
            RemoteNetworkId = remoteNetworkId;
        }
    }
}
