// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TwingateLabs.Twingate
{
    public static class GetTwingateGroups
    {
        public static Task<GetTwingateGroupsResult> InvokeAsync(GetTwingateGroupsArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetTwingateGroupsResult>("twingate:index/getTwingateGroups:getTwingateGroups", args ?? new GetTwingateGroupsArgs(), options.WithDefaults());

        public static Output<GetTwingateGroupsResult> Invoke(GetTwingateGroupsInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetTwingateGroupsResult>("twingate:index/getTwingateGroups:getTwingateGroups", args ?? new GetTwingateGroupsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTwingateGroupsArgs : Pulumi.InvokeArgs
    {
        [Input("isActive")]
        public bool? IsActive { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("type")]
        public string? Type { get; set; }

        public GetTwingateGroupsArgs()
        {
        }
    }

    public sealed class GetTwingateGroupsInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("isActive")]
        public Input<bool>? IsActive { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public GetTwingateGroupsInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetTwingateGroupsResult
    {
        public readonly ImmutableArray<Outputs.GetTwingateGroupsGroupResult> Groups;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool? IsActive;
        public readonly string? Name;
        public readonly string? Type;

        [OutputConstructor]
        private GetTwingateGroupsResult(
            ImmutableArray<Outputs.GetTwingateGroupsGroupResult> groups,

            string id,

            bool? isActive,

            string? name,

            string? type)
        {
            Groups = groups;
            Id = id;
            IsActive = isActive;
            Name = name;
            Type = type;
        }
    }
}
