// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getTwingateResources(args: GetTwingateResourcesArgs, opts?: pulumi.InvokeOptions): Promise<GetTwingateResourcesResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("twingate:index/getTwingateResources:getTwingateResources", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getTwingateResources.
 */
export interface GetTwingateResourcesArgs {
    name: string;
}

/**
 * A collection of values returned by getTwingateResources.
 */
export interface GetTwingateResourcesResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resources: outputs.GetTwingateResourcesResource[];
}

export function getTwingateResourcesOutput(args: GetTwingateResourcesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetTwingateResourcesResult> {
    return pulumi.output(args).apply(a => getTwingateResources(a, opts))
}

/**
 * A collection of arguments for invoking getTwingateResources.
 */
export interface GetTwingateResourcesOutputArgs {
    name: pulumi.Input<string>;
}
